name: Auto Tag Application with SemVer
on:
  push:
    branches:
      - main

concurrency: production
jobs:
  Version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Conventional Commits Version Bump
      uses: paulhatch/semantic-version@v5.3.0
      id: semver
      with:
        branch: main
        tag_prefix: "v"
        bump_each_commit: false
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
        search_commit_body: true
        enable_prerelease_mode: true
        debug: false

    - name: Apply new version tag 
      if: steps.semver.outputs.version
      uses: anothrNick/github-tag-action@1.36.0
      with:
        tag: ${{ steps.semver.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
