name: Auto Tag Application with SemVer
on:
  push:
    branches:
      - main

jobs:
  Version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
      with:
        fetch-depth: '0'

    - name: Conventional Commits Version Bump
      uses: paulhatch/semantic-version@v5.4.0 
      with:
        branch: main
        bump_each_commit: false
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        version_format: "${major}.${minor}.${patch}"
        search_commit_body: true
        enable_prerelease_mode: true
        tag_prefix: "v"
        debug: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
